"""added about_me and last_seen in user model

Revision ID: 216352b6c9a1
Revises: e0e61e65a08a
Create Date: 2019-09-17 13:53:39.258095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216352b6c9a1'
down_revision = 'e0e61e65a08a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
